#a> server Port, b> eureka client, c> Application Name d> datasource URL
#1>
server:
  port: 9092

#2>
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

#3>
spring:
  profiles:
    active: dev

  application:
    name: FOOD-CATALOGUE-SERVICE
  datasource:
    url: ${SPRING_DATASOURCE_URL} # Use the value from the environment variable
    password: ${SPRING_DATASOURCE_PASSWORD} # Use the value from the environment variable
    username: ${SPRING_DATASOURCE_USERNAME} # Use the value from the environment variable
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect