package com.manish.userinfo.mapper;

import com.manish.userinfo.dto.UserDTO;
import com.manish.userinfo.entity.User;
import org.springframework.stereotype.Component;

@Component
public class UserMapper {
    /*
    //Bot mapp function are static
    public static User mapUserDTOtoUserEntity(UserDTO userDTO) {
        User user = new User();
        user.setUserName(userDTO.getUserName());
        user.setUserPassword(userDTO.getUserPassword());
        user.setAddress(userDTO.getAddress());
        user.setCity(userDTO.getCity());
        return user;
    }

    public static UserDTO mapUserEntitytoUserDTO(User user) {
        UserDTO userDTO = new UserDTO();
        userDTO.setUserId(String.valueOf(user.getUserId()));
        userDTO.setUserName(user.getUserName());
        userDTO.setUserPassword(user.getUserPassword());
        userDTO.setAddress(user.getAddress());
        userDTO.setCity(user.getCity());
        return userDTO;
    }
     */

    public User mapUserDTOtoUserEntity(UserDTO userDTO) {
        if (userDTO == null) {
            return null;
        }

        User user = new User();
        // No need to set userId as it is auto-generated by the database
        // user.setUserId(userDTO.getUserId());
        user.setUserName(userDTO.getUserName());
        user.setUserPassword(userDTO.getUserPassword());
        user.setAddress(userDTO.getAddress());
        user.setCity(userDTO.getCity());

        return user;
    }

    public UserDTO mapUserEntitytoUserDTO(User user) {
        if (user == null) {
            return null;
        }

        UserDTO userDTO = new UserDTO();
        userDTO.setUserId(user.getUserId());
        userDTO.setUserName(user.getUserName());
        userDTO.setUserPassword(user.getUserPassword());
        userDTO.setAddress(user.getAddress());
        userDTO.setCity(user.getCity());

        return userDTO;
    }
}

