server:
  port: 9093


#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

spring:
  profiles:
    active: dev
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/userdb // mysql-db-instance.ch8kwgiu4x5q.eu-west-2.rds.amazonaws.com:3306/userdb
#    The password of DB
    password: 2122
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect