eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    service-url:
      defaultZone: http://eureka-0.eureka-service.default.svc.cluster.local:8761/eureka

spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin175@cluster0.cv01h.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0 # mongodb://localhost:27017/orderdb
      host: cluster0.cv01h.mongodb.net
      port: 27017
      database: orderdb
      repositories:
        enabled: true