
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  profiles:
    active: dev
  application:
    name: ORDER-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017/orderdb
      repositories:
        enabled: true