package com.manish.foodcatalogue.mapper;

import com.manish.foodcatalogue.dto.FoodItemDTO;
import com.manish.foodcatalogue.entity.FoodItem;
import org.springframework.stereotype.Component;

@Component
public class FoodItemMapper {
    public FoodItem mapFoodItemDTOToFoodItem(FoodItemDTO foodItemDTO) {
        if (foodItemDTO == null) {
            return null;
        }

        FoodItem foodItem = new FoodItem();
        // No need to set userId as it is auto-generated by the database
//        foodItem.setId(foodItemDTO.getId());
        foodItem.setItemName(foodItemDTO.getItemName());
        foodItem.setItemDescription(foodItemDTO.getItemDescription());
        foodItem.setVeg(foodItemDTO.isVeg());
        foodItem.setPrice(foodItemDTO.getPrice());
        foodItem.setRestaurantId(foodItemDTO.getRestaurantId());
        foodItem.setQuantity(foodItemDTO.getQuantity());

        return foodItem;
    }

    public FoodItemDTO mapFoodItemToFoodItemDTO(FoodItem foodItem) {
        if (foodItem == null) {
            return null;
        }

        FoodItemDTO foodItemDTO = new FoodItemDTO();

        foodItemDTO.setId(foodItem.getId());
        foodItemDTO.setItemName(foodItem.getItemName());
        foodItemDTO.setItemDescription(foodItem.getItemDescription());
        foodItemDTO.setVeg(foodItem.isVeg());
        foodItemDTO.setPrice(foodItem.getPrice());
        foodItemDTO.setRestaurantId(foodItem.getRestaurantId());
        foodItemDTO.setQuantity(foodItem.getQuantity());

        return foodItemDTO;
    }
}
